### ISSUE TITLE
magician's wand

### ISSUE THREAD

**Issue by woggy** [woggy/HekaCraft#17]
This is an item used in crafting the magician's table. should it have utility beyond use as a component?

**Comment by wolfwine** [comment]
Component for other magical tools crafted in the workbench, I don't think the base item does anything specific because everything I can imagine doing is something that really ought to be crafted in the workbench. ;P

Crafting recipe to start out with, subject to further tinkering:

__N
P_P
_PX

P for plank, N for gold nugget.  I can't decide whether I want the X to be another plank, lapis, or malachite, though.
